apiVersion: v1
kind: Pod
metadata:
    name: nginxpod
    labels:
        team: integrations
        app: nginxpod
        run: nginxpod
        environment: dev
spec:
    containers:
    -   name: nginxpod
        image: nginx:latest
        ports:
        - containerPort: 80