apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  labels:
    app: my-nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginxpod
  ports:
  - name: nginxpod
    port: 8082
    targetPort: 80
    protocol: TCP
    nodePort: 30000
  - name: nginx-replicaset
    port: 8083
    targetPort: 80
    protocol: TCP
    nodePort: 30002
 
