apiVersion: v1
kind: Pod
metadata:
    name: nginx-pods
    labels:
        team: integrations
        app: nginx-pods
        run: nginx-pods
spec:
    containers:
        -   name: nginx-container
            image: nginx:latest
            ports:
                -   containerPort: 80