apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
    labels: 
      env: dev
      role: App-Deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      role: App-Deploy
  template:
    metadata:
      name: nginx-deployment-template
      labels:
        role: App-Deploy
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80