apiVersion: v1
kind: Pod
metadata:
    name: nginx-pod2
    labels:
        team: integrations
        app: App-Pod2
spec:
    containers:
        -   name: nginx-container
            image: nginx:latest
            ports:
                -   containerPort: 80