apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  labels:
    app: my-nginx-service
spec:
  selector:
    app: nginx-pods
  ports:
  - port: 8082
    targetPort: 80
    protocol: TCP
 
